# .github/workflows/ci.yml
name: CI Test Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Say hello
        run: echo "✅ GitHub Actions workflow ran successfully!"

